name: Validate Gradle Wrapper

on: [push, pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: gradle/actions/wrapper-validation@v4
